baseURL = 'https://pub.jmnorlund.net/'
languageCode = 'en-us'
title = 'jmn public notes'
theme = "PaperMod"
ignoreErrors = ["error-remote-getjson"]

[params]
  google_fonts = [
    ["Fira Code", "400, 700"],
    ["Overpass Mono", "400, 400i, 700, 700i"]
  ]

  heading_font = "Fira Code"
  body_font = "Overpass Mono"
